### PR TITLE
mEBM explain global

### PR DESCRIPTION
**Pull request by JoshuaC3**
Add `explain_global` method to ExplainableBoostedMetaRegressor to aid in plotting feature importance's etc.

### CODE REVIEW

**Comment by Garve** [comment]
Hi!

Looks great, thank you! :)

Best
Robert

**Comment by RobKuebler** [comment]
Fixed and merged! Thanks.

**Comment by JoshuaC3** [comment]
Great! Maybe I had an different version of Interpret installed as I hadn't seen this error previously. thanks for fixing this.

**Comment by JoshuaC3** [comment]
I should have added in the notes, that I don't replicate the std bounds. I hadn't given it enough thought about how to process these, and it might be that this needs doing at training time. I believe this is how it is done in Interprets EBMs. Anyway, hopefully this is useful for yourself and others. Your implementation of Meta-EBM (I've been calling it mEBM) is really awesome!!

**Comment by RobKuebler** [comment]
Regarding the error:
It's not really an error that would break anything. Just in the scikit-learn ecosystem, you are not supposed to set values during init (e.g. your self.feature_name = None is forbidden).
And it's also not allowed to introduce new attributes that don't end with an "_".

I'm also not sure why, but that's the way it is at the moment :D

Your code works fine though!

**Comment by JoshuaC3** [comment]
Ok! Thanks. That's good to know. I was trying to follow the Interpret API for consistency but there we go!

**Pull request merged**
